import type { ListingOpportunity } from "./types";

export const MOCK_LISTINGS: ListingOpportunity[] = [
  {
    id: "mock-1",
    source: "source_d",
    operation: "sale",
    housingType: "flat",
    status: "active",
    canonicalUrl: "https://www.idealista.com/inmueble/111192450/",
    addressApprox: "Avenida Almogavares, Valdeolleros",
    city: "cordoba",
    zone: "Valdeolleros",
    lat: 37.898739,
    lng: -4.779755,
    builtArea: 71,
    rooms: 2,
    bathrooms: 1,
    floor: "2",
    price: 155000,
    pricePerMeter: 2183,
    currency: "EUR",
    mainImageUrl: null,
    imageUrls: [],
    description:
      "Magnifico piso reformado en Valdeolleros. Dos habitaciones, salon amplio con balcon, cocina equipada. Ascensor.",
    listingReference: "VES250414SM",
    cadastralRef: null,
    detailFetchedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    phoneCanonical: "+34600111222",
    advertiserId: "adv-mock-1",
    advertiserDisplayName: "Inmolike",
    advertiserType: "agency",
    inmovillaContactId: null,
    assignedComercialId: null,
    assignedComercialNombre: null,
    assignedAt: null,
    captacionStage: "NEW",
    inmovillaProspectRef: null,
    inmovillaPropertyCodOfer: null,
    captacionLastError: null,
    captacionUpdatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "mock-2",
    source: "source_b",
    operation: "sale",
    housingType: "flat",
    status: "active",
    canonicalUrl: "https://www.pisos.com/comprar/piso-cordoba_capital-12345/",
    addressApprox: "Calle Cruz Conde 12",
    city: "cordoba",
    zone: "Centro",
    lat: 37.879,
    lng: -4.7806,
    builtArea: 110,
    rooms: 3,
    bathrooms: 2,
    floor: "3",
    price: 240000,
    pricePerMeter: 2181,
    currency: "EUR",
    mainImageUrl: null,
    imageUrls: [],
    description:
      "Piso amplio en pleno Centro. Tres dormitorios, dos banos, terraza con vistas. Calefaccion central.",
    listingReference: "PC-MOCK-2",
    cadastralRef: null,
    detailFetchedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    phoneCanonical: "+34657334221",
    advertiserId: "adv-mock-2",
    advertiserDisplayName: "Maria Lopez",
    advertiserType: "particular",
    inmovillaContactId: "INM-998",
    assignedComercialId: "com-1",
    assignedComercialNombre: "Marina",
    assignedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    captacionStage: "PROSPECT_CREATED",
    inmovillaProspectRef: "MK-MOCK-2",
    inmovillaPropertyCodOfer: null,
    captacionLastError: null,
    captacionUpdatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "mock-3",
    source: "source_a",
    operation: "sale",
    housingType: "flat",
    status: "active",
    canonicalUrl:
      "https://www.fotocasa.es/es/comprar/vivienda/cordoba-capital/aire-ascensor/189164577/d",
    addressApprox: null,
    city: "cordoba",
    zone: null,
    lat: null,
    lng: null,
    builtArea: 95,
    rooms: 3,
    bathrooms: 2,
    floor: null,
    price: 185000,
    pricePerMeter: 1947,
    currency: "EUR",
    mainImageUrl: null,
    imageUrls: [],
    description: null,
    listingReference: null,
    cadastralRef: null,
    detailFetchedAt: null,
    phoneCanonical: null,
    advertiserId: null,
    advertiserDisplayName: null,
    advertiserType: null,
    inmovillaContactId: null,
    assignedComercialId: null,
    assignedComercialNombre: null,
    assignedAt: null,
    captacionStage: "FAILED",
    inmovillaProspectRef: null,
    inmovillaPropertyCodOfer: null,
    captacionLastError: "Falta key_loca para crear prospecto",
    captacionUpdatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
  },
];
