
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * URL dummy solo para `prisma generate` en CI/Railway/Nixpacks cuando aún no
 * existe DATABASE_URL (p. ej. durante `npm ci` → postinstall). No se conecta a
 * la DB; la URL real debe inyectarse en runtime y para migrate/deploy.
 */
const BUILD_PLACEHOLDER_DATABASE_URL =
  "postgresql://build:build@127.0.0.1:5432/build?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? BUILD_PLACEHOLDER_DATABASE_URL,
  },
});
