import type { Match } from "./types";

export const matches: Match[] = [
    { id: "match-1", propiedad: { id: "prop-1", direccion: "Calle Mayor 12, 3ºA", precio: 285000, metros: 95, habitaciones: 3, zona: "Centro" }, comprador: { nombre: "Ana García López", presupuestoMax: 300000, zonasInteres: ["Centro", "Ensanche"] }, porcentajeMatch: 92, variablesCoincidentes: ["precio", "zona", "habitaciones", "metros"], estadoMensaje: "me_encaja", fechaMatch: "2026-02-12T15:30:00Z" },
    { id: "match-2", propiedad: { id: "prop-7", direccion: "Av. del Puerto 88", precio: 380000, metros: 120, habitaciones: 3, zona: "Marítimo" }, comprador: { nombre: "Pedro Sánchez Ruiz", presupuestoMax: 400000, zonasInteres: ["Marítimo", "Malvarrosa"] }, porcentajeMatch: 88, variablesCoincidentes: ["precio", "zona", "habitaciones"], estadoMensaje: "enviado", fechaMatch: "2026-02-12T18:00:00Z" },
    { id: "match-3", propiedad: { id: "prop-9", direccion: "Blasco Ibáñez 62, 8ºA", precio: 245000, metros: 80, habitaciones: 2, zona: "Benimaclet" }, comprador: { nombre: "Laura Martín Vega", presupuestoMax: 260000, zonasInteres: ["Benimaclet", "Campanar"] }, porcentajeMatch: 85, variablesCoincidentes: ["precio", "zona", "metros"], estadoMensaje: "me_encaja", fechaMatch: "2026-02-11T10:00:00Z" },
    { id: "match-4", propiedad: { id: "prop-2", direccion: "Av. Constitución 45, 1ºB", precio: 420000, metros: 130, habitaciones: 4, zona: "Ensanche" }, comprador: { nombre: "Carlos Fernández", presupuestoMax: 400000, zonasInteres: ["Ensanche", "Centro"] }, porcentajeMatch: 72, variablesCoincidentes: ["zona", "habitaciones"], estadoMensaje: "no_encaja", fechaMatch: "2026-02-10T14:00:00Z" },
    { id: "match-5", propiedad: { id: "prop-4", direccion: "Calle Colón 23", precio: 550000, metros: 160, habitaciones: 4, zona: "Colón" }, comprador: { nombre: "Inversiones Sol SL", presupuestoMax: 600000, zonasInteres: ["Colón", "Centro", "Ensanche"] }, porcentajeMatch: 95, variablesCoincidentes: ["precio", "zona", "habitaciones", "metros"], estadoMensaje: "me_encaja", fechaMatch: "2026-02-12T09:00:00Z" },
    { id: "match-6", propiedad: { id: "prop-6", direccion: "Calle Ruzafa 15, Bajo", precio: 175000, metros: 55, habitaciones: 1, zona: "Ruzafa" }, comprador: { nombre: "María José Blanco", presupuestoMax: 200000, zonasInteres: ["Ruzafa", "Russafa"] }, porcentajeMatch: 90, variablesCoincidentes: ["precio", "zona", "metros"], estadoMensaje: "busco_diferente", fechaMatch: "2026-02-09T16:00:00Z" },
    { id: "match-7", propiedad: { id: "prop-11", direccion: "Calle Sorní 18, 4ºB", precio: 340000, metros: 110, habitaciones: 3, zona: "Ensanche" }, comprador: { nombre: "Roberto Díaz Navarro", presupuestoMax: 350000, zonasInteres: ["Ensanche"] }, porcentajeMatch: 94, variablesCoincidentes: ["precio", "zona", "habitaciones", "metros"], estadoMensaje: "enviado", fechaMatch: "2026-02-12T20:00:00Z" },
    { id: "match-8", propiedad: { id: "prop-12", direccion: "Av. Francia 20, 10ºA", precio: 620000, metros: 180, habitaciones: 4, zona: "Ciudad de las Artes" }, comprador: { nombre: "Grupo Inmobiliario Valencia", presupuestoMax: 650000, zonasInteres: ["Ciudad de las Artes", "Marítimo"] }, porcentajeMatch: 91, variablesCoincidentes: ["precio", "zona", "habitaciones"], estadoMensaje: "me_encaja", fechaMatch: "2026-02-11T12:00:00Z" },
];
