import type { PricingAnalysisResult } from "@/lib/pricing/types";

/**
 * Fixture estático de PricingAnalysisResult para revisar la UI con ?mock=1
 * sin depender de Neon, Statefox ni OpenAI.
 */
export const pricingFixture: PricingAnalysisResult = {
  propertyCode: "MOCK-001",
  input: {
    propertyCode: "MOCK-001",
    precio: 285000,
    precioM2: 3000,
    metrosConstruidos: 95,
    habitaciones: 3,
    banyos: 2,
    ciudad: "Córdoba",
    zona: "Centro",
    tipologiaNombre: "Piso",
    keyTipo: 1,
    tipoOperacion: "sale",
    estado: "En venta",
    fechaAlta: "2025-11-15",
    fechaActualizacion: "2026-04-05",
    extras: {
      terraza: true,
      garaje: false,
      ascensor: true,
      trastero: false,
      piscina: false,
      aireAcondicionado: true,
      calefaccion: "Central",
      anoConstruccion: "2005",
      certificadoEnergetico: "D",
    },
  },
  comparables: [
    {
      statefoxId: "sf-001",
      precio: 260000,
      precioM2: 2810,
      metrosConstruidos: 92,
      habitaciones: 3,
      banyos: 2,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "professional",
      extras: { terraza: true, ascensor: true },
      link: "https://www.idealista.com/inmueble/100001/",
      diasPublicado: 15,
      descripcion: "Luminoso piso de 3 habitaciones con terraza y vistas al casco histórico. Reformado en 2019, cocina equipada, suelos de gres porcelánico. Zona muy bien comunicada.",
      direccion: "Calle San Fernando 12, Centro, Córdoba",
      fotos: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80",
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80",
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
      ],
      anunciante: { nombre: "Inmobiliaria Cervantes", tipo: "professional", telefonos: ["+34957221100"] },
      latitud: 37.8847,
      longitud: -4.7792,
      planta: "3ª",
      orientacion: "Sur",
      referencia: "IDL-100001",
    },
    {
      statefoxId: "sf-002",
      precio: 275000,
      precioM2: 2890,
      metrosConstruidos: 95,
      habitaciones: 3,
      banyos: 1,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "private",
      extras: { terraza: false, garaje: true, ascensor: true },
      link: "https://www.idealista.com/inmueble/100002/",
      diasPublicado: 22,
      descripcion: "Piso particular en pleno centro. Garaje incluido en precio. Necesita actualización de baño. Comunidad baja.",
      direccion: "Avenida del Gran Capitán 8, Centro, Córdoba",
      fotos: [
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
        "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=600&q=80",
      ],
      anunciante: { nombre: null, tipo: "private", telefonos: ["+34612345678"] },
      latitud: 37.8862,
      longitud: -4.7805,
      planta: "2ª",
      orientacion: "Este",
      referencia: "IDL-100002",
    },
    {
      statefoxId: "sf-003",
      precio: 295000,
      precioM2: 3100,
      metrosConstruidos: 95,
      habitaciones: 3,
      banyos: 2,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "professional",
      extras: { terraza: true, garaje: true, ascensor: true, aireAcondicionado: true },
      link: "https://www.fotocasa.es/es/comprar/vivienda/cordoba/100003",
      diasPublicado: 8,
      descripcion: "Espectacular piso totalmente reformado con acabados de alta calidad. Terraza de 15m², plaza de garaje y trastero. Certificado energético B. Calefacción central.",
      direccion: "Plaza de las Tendillas 3, Centro, Córdoba",
      fotos: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80",
        "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80",
      ],
      anunciante: { nombre: "Fincas González", tipo: "professional", telefonos: ["+34957334455", "+34600112233"] },
      latitud: 37.8841,
      longitud: -4.7770,
      planta: "4ª",
      orientacion: "Sur-Oeste",
      referencia: "FC-100003",
    },
    {
      statefoxId: "sf-004",
      precio: 240000,
      precioM2: 2670,
      metrosConstruidos: 90,
      habitaciones: 2,
      banyos: 1,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "private",
      extras: { ascensor: true },
      link: "https://example.com/sf-004",
      diasPublicado: 35,
      descripcion: "Piso de 2 habitaciones, necesita reforma. Buena ubicación a 5 minutos de la Mezquita. Ideal como inversión.",
      direccion: "Calle Claudio Marcelo 5, Centro, Córdoba",
      fotos: [
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
      ],
      anunciante: { nombre: null, tipo: "private", telefonos: ["+34655998877"] },
      latitud: 37.8835,
      longitud: -4.7760,
      planta: "1ª",
      orientacion: null,
      referencia: null,
    },
    {
      statefoxId: "sf-005",
      precio: 310000,
      precioM2: 3180,
      metrosConstruidos: 97,
      habitaciones: 3,
      banyos: 2,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "professional",
      extras: { terraza: true, garaje: true, ascensor: true, trastero: true },
      link: "https://www.idealista.com/inmueble/100005/",
      diasPublicado: 5,
      descripcion: "Exclusivo piso con terraza panorámica, garaje doble y trastero. Calidades premium: suelos de mármol, domótica, doble acristalamiento. A estrenar tras reforma integral.",
      direccion: "Paseo de la Victoria 22, Centro, Córdoba",
      fotos: [
        "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80",
        "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&q=80",
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=80",
      ],
      anunciante: { nombre: "RE/MAX Élite Córdoba", tipo: "professional", telefonos: ["+34957889900"] },
      latitud: 37.8870,
      longitud: -4.7830,
      planta: "5ª",
      orientacion: "Norte",
      referencia: "IDL-100005",
    },
    {
      statefoxId: "sf-006",
      precio: 255000,
      precioM2: 2750,
      metrosConstruidos: 93,
      habitaciones: 3,
      banyos: 1,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "private",
      extras: { terraza: false, ascensor: false },
      link: null,
      diasPublicado: 45,
      descripcion: "Piso sin ascensor en finca de 3 plantas. Buen estado general aunque necesita actualización de instalaciones. Sin terraza.",
      direccion: "Calle Alfonso XIII 17, Centro, Córdoba",
      fotos: [],
      anunciante: { nombre: null, tipo: "private", telefonos: [] },
      latitud: 37.8852,
      longitud: -4.7812,
      planta: "2ª",
      orientacion: "Oeste",
      referencia: null,
    },
  ],
  stats: {
    totalComparables: 6,
    precioMedioM2: 2900,
    precioMedianaM2: 2850,
    precioMinM2: 2670,
    precioMaxM2: 3180,
    desviacionEstandar: 185.4,
    precioMedioM2Particular: 2770,
    precioMedioM2Profesional: 2970,
    gapPorcentaje: 3.45,
    semaforo: "verde",
  },
  analyzedAt: new Date().toISOString(),
  trend: {
    propertyAgeDays: 144,
    lastUpdatedDays: 2,
    comparableAverageDaysPublished: 21.67,
    comparableMedianDaysPublished: 18.5,
    freshComparablesShare: 0.33,
    staleComparablesShare: 0.17,
    marketTempo: "estable",
    listingMomentum: "estancado",
    pressure: "media",
    summary:
      "El inmueble lleva 144 días en cartera; la ficha se actualizó hace 2 días. El mercado va estable (media 21.67 días publicados en comparables). 33% de comparables son recientes y 17% llevan mucho tiempo publicados. La presión temporal actual es media.",
  },
  queryMeta: {
    endpoint: "snapshot",
    housing: "flat",
    type: "sale",
    pagesScanned: 12,
    totalResultsFromAPI: 3000,
    filteredResults: 6,
  },
  recommendation: {
    accion: "mantener",
    diagnostico:
      "El inmueble MOCK-001 en Córdoba Centro presenta un gap de +3.45% respecto a la media del cluster (2.900 €/m²), dentro del umbral verde (≤5%). Con 6 comparables analizados, el precio de 3.000 €/m² se sitúa ligeramente por encima de la mediana (2.850 €/m²) pero dentro del rango competitivo. La segmentación muestra que los profesionales publican a 2.970 €/m² de media, lo que valida el posicionamiento actual.",
    recomendaciones: [
      "Mantener el precio actual de 285.000 € y monitorizar semanalmente la posición respecto al cluster.",
      "Destacar en el anuncio los extras diferenciadores: terraza, ascensor y aire acondicionado central.",
      "Considerar fotografía profesional para mejorar la tasa de clics frente a los 3 comparables profesionales con más extras.",
      "Si en 2 semanas no se generan leads, evaluar un ajuste ligero del 2-3% para posicionarse por debajo de la mediana.",
    ],
    precioSugeridoMin: null,
    precioSugeridoMax: null,
    argumentosComerciales: [
      "Terraza incluida, solo 2 de 6 comparables la tienen",
      "Aire acondicionado central instalado",
      "Ascensor disponible",
      "Año de construcción 2005 — edificio relativamente moderno",
    ],
    riesgos: [
      "3 comparables profesionales con más extras (garaje + trastero) pueden captar leads antes",
      "El comparable sf-005 a 310.000 € tiene más extras por un diferencial mínimo de precio",
    ],
    confidence: 0.82,
    reasoning:
      "Gap +3.45% dentro de umbral verde. Cluster de 6 comparables con dispersión moderada (σ=185€/m²). Inmueble competitivo pero sin ventaja clara en extras frente a los profesionales del top del cluster.",
  },
};

/**
 * Fixture de listado de propiedades para ?mock=1 en /pricing.
 */
export const propertiesListFixture = [
  {
    codigo: "MOCK-001",
    ref: "R-001",
    titulo: "Piso en Centro",
    tipoOfer: "1",
    precio: 285000,
    metrosConstruidos: 95,
    habitaciones: 3,
    banyos: 2,
    ciudad: "Córdoba",
    zona: "Centro",
    estado: "En venta",
    numFotos: 12,
    agente: "Ana García",
    fechaAlta: "2025-11-15",
    mainPhotoUrl:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    portalUrl: "https://www.idealista.com/inmueble/111223929/",
    portalName: "idealista",
  },
  {
    codigo: "MOCK-002",
    ref: "R-002",
    titulo: "Ático en Ensanche",
    tipoOfer: "1",
    precio: 420000,
    metrosConstruidos: 130,
    habitaciones: 4,
    banyos: 2,
    ciudad: "Córdoba",
    zona: "Ensanche",
    estado: "En venta",
    numFotos: 18,
    agente: "Carlos López",
    fechaAlta: "2025-10-20",
    mainPhotoUrl:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80&auto=format&fit=crop",
    portalUrl: "https://www.idealista.com/inmueble/111223930/",
    portalName: "idealista",
  },
  {
    codigo: "MOCK-003",
    ref: "R-003",
    titulo: "Estudio en Ruzafa",
    tipoOfer: "1",
    precio: 175000,
    metrosConstruidos: 55,
    habitaciones: 1,
    banyos: 1,
    ciudad: "Córdoba",
    zona: "Ruzafa",
    estado: "En venta",
    numFotos: 8,
    agente: "Ana García",
    fechaAlta: "2025-09-01",
    mainPhotoUrl:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    portalUrl: null,
    portalName: null,
  },
  {
    codigo: "MOCK-004",
    ref: "R-004",
    titulo: "Chalet en Politécnico",
    tipoOfer: "1",
    precio: 520000,
    metrosConstruidos: 200,
    habitaciones: 5,
    banyos: 3,
    ciudad: "Córdoba",
    zona: "Politécnico",
    estado: "En venta",
    numFotos: 25,
    agente: "María Ruiz",
    fechaAlta: "2025-12-01",
    mainPhotoUrl:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80&auto=format&fit=crop",
    portalUrl: "https://www.fotocasa.es/es/comprar/vivienda/cordoba/zona-politecnico/189012345",
    portalName: "fotocasa",
  },
  {
    codigo: "MOCK-005",
    ref: "R-005",
    titulo: "Piso en Marítimo",
    tipoOfer: "1",
    precio: 380000,
    metrosConstruidos: 120,
    habitaciones: 3,
    banyos: 2,
    ciudad: "Córdoba",
    zona: "Marítimo",
    estado: "Reservado",
    numFotos: 15,
    agente: "Carlos López",
    fechaAlta: "2026-01-10",
    mainPhotoUrl: null,
    portalUrl: null,
    portalName: null,
  },
];
