import type { PricingAnalysisResult } from "@/lib/pricing/types";

/**
 * Fixture estático de PricingAnalysisResult para revisar la UI con ?mock=1
 * sin depender de Neon, Statefox ni OpenAI.
 */
export const pricingFixture: PricingAnalysisResult = {
  propertyCode: "MOCK-001",
  input: {
    propertyCode: "MOCK-001",
    precio: 285000,
    precioM2: 3000,
    metrosConstruidos: 95,
    habitaciones: 3,
    banyos: 2,
    ciudad: "Córdoba",
    zona: "Centro",
    tipologiaNombre: "Piso",
    keyTipo: 1,
    tipoOperacion: "sale",
    estado: "En venta",
    fechaAlta: "2025-11-15",
    fechaActualizacion: "2026-04-05",
    extras: {
      terraza: true,
      garaje: false,
      ascensor: true,
      trastero: false,
      piscina: false,
      aireAcondicionado: true,
      calefaccion: "Central",
      anoConstruccion: "2005",
      certificadoEnergetico: "D",
    },
  },
  comparables: [
    {
      statefoxId: "sf-001",
      precio: 260000,
      precioM2: 2810,
      metrosConstruidos: 92,
      habitaciones: 3,
      banyos: 2,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "professional",
      extras: { terraza: true, ascensor: true },
      link: "https://example.com/sf-001",
      diasPublicado: 15,
    },
    {
      statefoxId: "sf-002",
      precio: 275000,
      precioM2: 2890,
      metrosConstruidos: 95,
      habitaciones: 3,
      banyos: 1,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "private",
      extras: { terraza: false, garaje: true, ascensor: true },
      link: "https://example.com/sf-002",
      diasPublicado: 22,
    },
    {
      statefoxId: "sf-003",
      precio: 295000,
      precioM2: 3100,
      metrosConstruidos: 95,
      habitaciones: 3,
      banyos: 2,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "professional",
      extras: { terraza: true, garaje: true, ascensor: true, aireAcondicionado: true },
      link: "https://example.com/sf-003",
      diasPublicado: 8,
    },
    {
      statefoxId: "sf-004",
      precio: 240000,
      precioM2: 2670,
      metrosConstruidos: 90,
      habitaciones: 2,
      banyos: 1,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "private",
      extras: { ascensor: true },
      link: "https://example.com/sf-004",
      diasPublicado: 35,
    },
    {
      statefoxId: "sf-005",
      precio: 310000,
      precioM2: 3180,
      metrosConstruidos: 97,
      habitaciones: 3,
      banyos: 2,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "professional",
      extras: { terraza: true, garaje: true, ascensor: true, trastero: true },
      link: "https://example.com/sf-005",
      diasPublicado: 5,
    },
    {
      statefoxId: "sf-006",
      precio: 255000,
      precioM2: 2750,
      metrosConstruidos: 93,
      habitaciones: 3,
      banyos: 1,
      ciudad: "Córdoba",
      zona: "Centro",
      tipologia: "flat",
      advertiserType: "private",
      extras: { terraza: false, ascensor: false },
      link: null,
      diasPublicado: 45,
    },
  ],
  stats: {
    totalComparables: 6,
    precioMedioM2: 2900,
    precioMedianaM2: 2850,
    precioMinM2: 2670,
    precioMaxM2: 3180,
    desviacionEstandar: 185.4,
    precioMedioM2Particular: 2770,
    precioMedioM2Profesional: 2970,
    gapPorcentaje: 3.45,
    semaforo: "verde",
  },
  analyzedAt: new Date().toISOString(),
  trend: {
    propertyAgeDays: 144,
    lastUpdatedDays: 2,
    comparableAverageDaysPublished: 21.67,
    comparableMedianDaysPublished: 18.5,
    freshComparablesShare: 0.33,
    staleComparablesShare: 0.17,
    marketTempo: "estable",
    listingMomentum: "estancado",
    pressure: "media",
    summary:
      "El inmueble lleva 144 días en cartera; la ficha se actualizó hace 2 días. El mercado va estable (media 21.67 días publicados en comparables). 33% de comparables son recientes y 17% llevan mucho tiempo publicados. La presión temporal actual es media.",
  },
  queryMeta: {
    endpoint: "snapshot",
    housing: "flat",
    type: "sale",
    pagesScanned: 12,
    totalResultsFromAPI: 3000,
    filteredResults: 6,
  },
  recommendation: {
    accion: "mantener",
    diagnostico:
      "El inmueble MOCK-001 en Córdoba Centro presenta un gap de +3.45% respecto a la media del cluster (2.900 €/m²), dentro del umbral verde (≤5%). Con 6 comparables analizados, el precio de 3.000 €/m² se sitúa ligeramente por encima de la mediana (2.850 €/m²) pero dentro del rango competitivo. La segmentación muestra que los profesionales publican a 2.970 €/m² de media, lo que valida el posicionamiento actual.",
    recomendaciones: [
      "Mantener el precio actual de 285.000 € y monitorizar semanalmente la posición respecto al cluster.",
      "Destacar en el anuncio los extras diferenciadores: terraza, ascensor y aire acondicionado central.",
      "Considerar fotografía profesional para mejorar la tasa de clics frente a los 3 comparables profesionales con más extras.",
      "Si en 2 semanas no se generan leads, evaluar un ajuste ligero del 2-3% para posicionarse por debajo de la mediana.",
    ],
    precioSugeridoMin: null,
    precioSugeridoMax: null,
    argumentosComerciales: [
      "Terraza incluida, solo 2 de 6 comparables la tienen",
      "Aire acondicionado central instalado",
      "Ascensor disponible",
      "Año de construcción 2005 — edificio relativamente moderno",
    ],
    riesgos: [
      "3 comparables profesionales con más extras (garaje + trastero) pueden captar leads antes",
      "El comparable sf-005 a 310.000 € tiene más extras por un diferencial mínimo de precio",
    ],
    confidence: 0.82,
    reasoning:
      "Gap +3.45% dentro de umbral verde. Cluster de 6 comparables con dispersión moderada (σ=185€/m²). Inmueble competitivo pero sin ventaja clara en extras frente a los profesionales del top del cluster.",
  },
};

/**
 * Fixture de listado de propiedades para ?mock=1 en /pricing.
 */
export const propertiesListFixture = [
  { codigo: "MOCK-001", ref: "R-001", titulo: "Piso en Centro", tipoOfer: "1", precio: 285000, metrosConstruidos: 95, habitaciones: 3, banyos: 2, ciudad: "Córdoba", zona: "Centro", estado: "En venta", numFotos: 12, agente: "Ana García", fechaAlta: "2025-11-15" },
  { codigo: "MOCK-002", ref: "R-002", titulo: "Ático en Ensanche", tipoOfer: "1", precio: 420000, metrosConstruidos: 130, habitaciones: 4, banyos: 2, ciudad: "Córdoba", zona: "Ensanche", estado: "En venta", numFotos: 18, agente: "Carlos López", fechaAlta: "2025-10-20" },
  { codigo: "MOCK-003", ref: "R-003", titulo: "Estudio en Ruzafa", tipoOfer: "1", precio: 175000, metrosConstruidos: 55, habitaciones: 1, banyos: 1, ciudad: "Córdoba", zona: "Ruzafa", estado: "En venta", numFotos: 8, agente: "Ana García", fechaAlta: "2025-09-01" },
  { codigo: "MOCK-004", ref: "R-004", titulo: "Chalet en Politécnico", tipoOfer: "1", precio: 520000, metrosConstruidos: 200, habitaciones: 5, banyos: 3, ciudad: "Córdoba", zona: "Politécnico", estado: "En venta", numFotos: 25, agente: "María Ruiz", fechaAlta: "2025-12-01" },
  { codigo: "MOCK-005", ref: "R-005", titulo: "Piso en Marítimo", tipoOfer: "1", precio: 380000, metrosConstruidos: 120, habitaciones: 3, banyos: 2, ciudad: "Córdoba", zona: "Marítimo", estado: "Reservado", numFotos: 15, agente: "Carlos López", fechaAlta: "2026-01-10" },
];
