import type { Propiedad } from "./types";

export const propiedades: Propiedad[] = [
    { id: "prop-1", direccion: "Calle Mayor 12, 3ºA", precio: 285000, metros: 95, habitaciones: 3, zona: "Centro", tipologia: "Piso", estado: "En venta", semaforo: "verde", diasSinLlamadas: 2, posicionPortal: 3, gapPrecio: -2.1, extras: { terraza: true, garaje: false, ascensor: true, reformado: true } },
    { id: "prop-2", direccion: "Av. Constitución 45, 1ºB", precio: 420000, metros: 130, habitaciones: 4, zona: "Ensanche", tipologia: "Piso", estado: "En venta", semaforo: "amarillo", diasSinLlamadas: 12, posicionPortal: 7, gapPrecio: 5.3, extras: { terraza: true, garaje: true, ascensor: true, reformado: false } },
    { id: "prop-3", direccion: "Gran Vía 8, 5ºC", precio: 195000, metros: 65, habitaciones: 2, zona: "Gran Vía", tipologia: "Piso", estado: "En venta", semaforo: "rojo", diasSinLlamadas: 45, posicionPortal: 15, gapPrecio: 12.8, extras: { terraza: false, garaje: false, ascensor: true, reformado: false } },
    { id: "prop-4", direccion: "Calle Colón 23", precio: 550000, metros: 160, habitaciones: 4, zona: "Colón", tipologia: "Ático", estado: "En venta", semaforo: "verde", diasSinLlamadas: 1, posicionPortal: 1, gapPrecio: -5.2, extras: { terraza: true, garaje: true, ascensor: true, reformado: true } },
    { id: "prop-5", direccion: "Pl. Ayuntamiento 7, 2ºD", precio: 310000, metros: 100, habitaciones: 3, zona: "Centro", tipologia: "Piso", estado: "Reservado", semaforo: "verde", diasSinLlamadas: 0, posicionPortal: 2, gapPrecio: -1.5, extras: { terraza: false, garaje: true, ascensor: true, reformado: true } },
    { id: "prop-6", direccion: "Calle Ruzafa 15, Bajo", precio: 175000, metros: 55, habitaciones: 1, zona: "Ruzafa", tipologia: "Estudio", estado: "En venta", semaforo: "amarillo", diasSinLlamadas: 18, posicionPortal: 9, gapPrecio: 7.1, extras: { terraza: false, garaje: false, ascensor: false, reformado: true } },
    { id: "prop-7", direccion: "Av. del Puerto 88", precio: 380000, metros: 120, habitaciones: 3, zona: "Marítimo", tipologia: "Piso", estado: "En venta", semaforo: "verde", diasSinLlamadas: 4, posicionPortal: 4, gapPrecio: -0.8, extras: { terraza: true, garaje: true, ascensor: true, reformado: false } },
    { id: "prop-8", direccion: "Calle Caballeros 30", precio: 450000, metros: 140, habitaciones: 4, zona: "Carmen", tipologia: "Piso", estado: "En venta", semaforo: "rojo", diasSinLlamadas: 38, posicionPortal: 12, gapPrecio: 15.2, extras: { terraza: false, garaje: false, ascensor: true, reformado: false } },
    { id: "prop-9", direccion: "Blasco Ibáñez 62, 8ºA", precio: 245000, metros: 80, habitaciones: 2, zona: "Benimaclet", tipologia: "Piso", estado: "En venta", semaforo: "verde", diasSinLlamadas: 3, posicionPortal: 2, gapPrecio: -3.4, extras: { terraza: true, garaje: false, ascensor: true, reformado: true } },
    { id: "prop-10", direccion: "Camino de Vera 100", precio: 520000, metros: 200, habitaciones: 5, zona: "Politécnico", tipologia: "Chalet", estado: "En venta", semaforo: "amarillo", diasSinLlamadas: 22, posicionPortal: 6, gapPrecio: 4.6, extras: { terraza: true, garaje: true, ascensor: false, reformado: true } },
    { id: "prop-11", direccion: "Calle Sorní 18, 4ºB", precio: 340000, metros: 110, habitaciones: 3, zona: "Ensanche", tipologia: "Piso", estado: "En venta", semaforo: "verde", diasSinLlamadas: 5, posicionPortal: 3, gapPrecio: -1.2, extras: { terraza: false, garaje: true, ascensor: true, reformado: true } },
    { id: "prop-12", direccion: "Av. Francia 20, 10ºA", precio: 620000, metros: 180, habitaciones: 4, zona: "Ciudad de las Artes", tipologia: "Ático", estado: "En venta", semaforo: "verde", diasSinLlamadas: 1, posicionPortal: 1, gapPrecio: -6.8, extras: { terraza: true, garaje: true, ascensor: true, reformado: true } },
];
