-- Elimina jobs legacy de validación manual para poder limpiar el enum.
DELETE FROM "job_queue"
WHERE "type"::text IN ('NOTIFY_MICROSITE_PENDING_VALIDATION', 'AUTO_VALIDATE_MICROSITE');

-- Reemplaza el enum JobType sin variantes legacy.
CREATE TYPE "JobType_new" AS ENUM (
  'PROCESS_EVENT',
  'UPDATE_PROPERTY_PROJECTION',
  'UPDATE_DEMAND_PROJECTION',
  'WRITE_TO_INMOVILLA',
  'NOTIFY_LEAD_WHATSAPP',
  'FOLLOW_UP_LEAD',
  'GENERATE_MICROSITE',
  'SEND_MICROSITE_TO_BUYER',
  'NOTIFY_CONTRACT_DATA_INCOMPLETE',
  'GENERATE_CONTRACT_DRAFT',
  'SEND_SIGNATURE_REQUEST',
  'PROCESS_SIGNATURE_WEBHOOK',
  'NOTIFY_SIGNATURE_REMINDER',
  'RUN_PRICING_ANALYSIS',
  'NOTIFY_PRICING_WHATSAPP',
  'START_POSTVENTA_CADENCE',
  'SEND_POSTVENTA_MESSAGE',
  'SEND_POSTVENTA_FORM',
  'SCHEDULE_POSTVENTA_BIRTHDAY',
  'SCHEDULE_POSTVENTA_NAVIDAD',
  'SEND_POST_SALE_MESSAGE',
  'SEND_REVIEW_REQUEST',
  'SEND_REFERRAL_REQUEST',
  'SEND_REVIEW_REMINDER',
  'SEND_DEV_EXERCISE_NUDGE',
  'VISIT_FETCH_SLOTS',
  'VISIT_PROPOSE_TO_COMMERCIAL',
  'VISIT_PROPOSE_TO_BUYER',
  'VISIT_CHECK_COMMERCIAL_TIMEOUT',
  'VISIT_CHECK_BUYER_TIMEOUT',
  'VISIT_CREATE_CALENDAR_EVENT',
  'VISIT_CANCEL_CALENDAR_EVENT',
  'VISIT_CLEANUP_EXPIRED_LOCKS',
  'VISIT_CHECK_COMPOSIO_HEALTH',
  'NOTA_ENCARGO_RECORDATORIO',
  'NOTA_ENCARGO_CHECK_CONFIRMACION',
  'NOTA_ENCARGO_ENVIAR_FORMULARIO',
  'NOTA_ENCARGO_MATCHING_CHECK',
  'PARTE_VISITA_ENVIAR_FORMULARIO',
  'SEND_WHATSAPP_MATCH',
  'EVALUATE_DEMAND_COVERAGE',
  'REBUILD_MATCHES_FOR_DEMAND',
  'START_NLU_INITIAL_CONTACT',
  'MATCH_DEMAND_AGAINST_INTERNAL',
  'UPDATE_PROPERTY_STATUS_INMOVILLA',
  'SEND_BUYER_INTEREST_ACK',
  'IMPORT_STATEFOX_PORTAL_IMAGES',
  'MARKET_DISCOVER_SEEDS',
  'MARKET_CRAWL_SEED',
  'MARKET_FETCH_DETAIL',
  'MARKET_NORMALIZE_BATCH',
  'MARKET_RESOLVE_IDENTITY',
  'MARKET_RESOLVE_ADVERTISER',
  'MARKET_DIFF_AND_VERSION',
  'MARKET_REFRESH_SNAPSHOT',
  'MARKET_IMPORT_LISTING_IMAGES',
  'MARKET_RUN_RULES',
  'MARKET_REINDEX_PROPERTY',
  'MARKET_PUSH_ADVERTISER_TO_INMOVILLA'
);

ALTER TABLE "job_queue"
ALTER COLUMN "type" TYPE "JobType_new"
USING ("type"::text::"JobType_new");

DROP TYPE "JobType";
ALTER TYPE "JobType_new" RENAME TO "JobType";

-- Limpieza de columnas legacy de validación manual.
ALTER TABLE "comerciales"
DROP COLUMN IF EXISTS "autoValidateMicrosite";

DROP INDEX IF EXISTS "microsite_selections_status_validationDueAt_idx";

ALTER TABLE "microsite_selections"
DROP COLUMN IF EXISTS "validationToken",
DROP COLUMN IF EXISTS "validationDueAt",
DROP COLUMN IF EXISTS "validatedAt",
DROP COLUMN IF EXISTS "validatedByComercialId",
DROP COLUMN IF EXISTS "escalatedAt";
