-- AlterEnum: OperacionEstado — agregar OFERTA_FIRME
ALTER TYPE "OperacionEstado" ADD VALUE 'OFERTA_FIRME' BEFORE 'RESERVA';

-- AlterEnum: EventType — agregar OPERACION_CREADA, OPERACION_AVANZADA
ALTER TYPE "EventType" ADD VALUE 'OPERACION_CREADA';
ALTER TYPE "EventType" ADD VALUE 'OPERACION_AVANZADA';

-- AlterEnum: JobType — agregar UPDATE_PROPERTY_STATUS_INMOVILLA
ALTER TYPE "JobType" ADD VALUE 'UPDATE_PROPERTY_STATUS_INMOVILLA';
