-- AlterEnum: add DATOS_INCOMPLETOS to EventType
ALTER TYPE "EventType" ADD VALUE 'DATOS_INCOMPLETOS';

-- AlterEnum: add NOTIFY_CONTRACT_DATA_INCOMPLETE to JobType
ALTER TYPE "JobType" ADD VALUE 'NOTIFY_CONTRACT_DATA_INCOMPLETE';
