import type { ContractDocumentKind } from "@/types/contracts";
import type { VariableCatalogEntry, VariableCategory } from "@/types/contract-template";

const ALL_KINDS: ContractDocumentKind[] = ["arras", "senal_compra", "oferta_firme", "anexo_mobiliario"];

export const VARIABLE_CATALOG: VariableCatalogEntry[] = [
  // ── Comprador / Vendedor ──────────────────────────────────────────────────
  {
    path: "buyers[].fullName",
    label: "Nombre del comprador",
    category: "comprador_vendedor",
    tsType: "NaturalPerson.fullName",
    sourceType: "inmovilla",
    sourceDetail: "Se obtiene de la ficha del cliente en Inmovilla",
    applicableKinds: ["arras"],
    exampleValue: "Maria Lopez Garcia",
    isArray: true,
  },
  {
    path: "buyers[].nationalId",
    label: "DNI / NIE del comprador",
    category: "comprador_vendedor",
    tsType: "NaturalPerson.nationalId",
    sourceType: "inmovilla",
    sourceDetail: "Se obtiene de la ficha del cliente en Inmovilla",
    applicableKinds: ["arras"],
    exampleValue: "12345678A",
    isArray: true,
  },
  {
    path: "buyers[].fiscalAddress.streetLine",
    label: "Domicilio del comprador",
    category: "comprador_vendedor",
    tsType: "PostalAddress.streetLine",
    sourceType: "inmovilla",
    sourceDetail: "Direccion fiscal registrada en la ficha del cliente",
    applicableKinds: ["arras"],
    exampleValue: "C/ Gran Via 10, 3o B",
    isArray: true,
  },
  {
    path: "buyers[].fiscalAddress.municipality",
    label: "Ciudad del comprador",
    category: "comprador_vendedor",
    tsType: "PostalAddress.municipality",
    sourceType: "inmovilla",
    sourceDetail: "Localidad de la ficha del cliente",
    applicableKinds: ["arras"],
    exampleValue: "Madrid",
    isArray: true,
  },
  {
    path: "sellers[].fullName",
    label: "Nombre del vendedor",
    category: "comprador_vendedor",
    tsType: "NaturalPerson.fullName",
    sourceType: "inmovilla",
    sourceDetail: "Se obtiene de la ficha del cliente en Inmovilla",
    applicableKinds: ["arras"],
    exampleValue: "Pedro Martinez Ruiz",
    isArray: true,
  },
  {
    path: "sellers[].nationalId",
    label: "DNI / NIE del vendedor",
    category: "comprador_vendedor",
    tsType: "NaturalPerson.nationalId",
    sourceType: "inmovilla",
    sourceDetail: "Se obtiene de la ficha del cliente en Inmovilla",
    applicableKinds: ["arras"],
    exampleValue: "87654321B",
    isArray: true,
  },
  {
    path: "sellers[].fiscalAddress.streetLine",
    label: "Domicilio del vendedor",
    category: "comprador_vendedor",
    tsType: "PostalAddress.streetLine",
    sourceType: "inmovilla",
    sourceDetail: "Direccion fiscal registrada en la ficha del cliente",
    applicableKinds: ["arras"],
    exampleValue: "Av. Diagonal 450, 2o A",
    isArray: true,
  },
  {
    path: "sellers[].fiscalAddress.municipality",
    label: "Ciudad del vendedor",
    category: "comprador_vendedor",
    tsType: "PostalAddress.municipality",
    sourceType: "inmovilla",
    sourceDetail: "Localidad de la ficha del cliente",
    applicableKinds: ["arras"],
    exampleValue: "Barcelona",
    isArray: true,
  },
  {
    path: "purchaser.fullName",
    label: "Nombre del comprador",
    category: "comprador_vendedor",
    tsType: "NaturalPerson.fullName",
    sourceType: "inmovilla",
    sourceDetail: "Se obtiene de la ficha del cliente en Inmovilla",
    applicableKinds: ["senal_compra"],
    exampleValue: "Maria Lopez Garcia",
    isArray: false,
  },
  {
    path: "purchaser.nationalId",
    label: "DNI / NIE del comprador",
    category: "comprador_vendedor",
    tsType: "NaturalPerson.nationalId",
    sourceType: "inmovilla",
    sourceDetail: "Se obtiene de la ficha del cliente en Inmovilla",
    applicableKinds: ["senal_compra"],
    exampleValue: "12345678A",
    isArray: false,
  },
  {
    path: "offerers[].fullName",
    label: "Nombre del ofertante",
    category: "comprador_vendedor",
    tsType: "NaturalPerson.fullName",
    sourceType: "inmovilla",
    sourceDetail: "Se obtiene de la ficha del cliente en Inmovilla",
    applicableKinds: ["oferta_firme"],
    exampleValue: "Maria Lopez Garcia",
    isArray: true,
  },
  {
    path: "offerers[].nationalId",
    label: "DNI / NIE del ofertante",
    category: "comprador_vendedor",
    tsType: "NaturalPerson.nationalId",
    sourceType: "inmovilla",
    sourceDetail: "Se obtiene de la ficha del cliente en Inmovilla",
    applicableKinds: ["oferta_firme"],
    exampleValue: "12345678A",
    isArray: true,
  },

  // ── Inmueble ──────────────────────────────────────────────────────────────
  {
    path: "property.addressLine",
    label: "Direccion del inmueble",
    category: "inmueble",
    tsType: "string",
    sourceType: "neon",
    sourceDetail: "Direccion completa de la ficha de la propiedad",
    applicableKinds: ["arras", "senal_compra", "oferta_firme"],
    exampleValue: "C/ Serrano 25, 3o B",
    isArray: false,
  },
  {
    path: "property.municipality",
    label: "Ciudad del inmueble",
    category: "inmueble",
    tsType: "string",
    sourceType: "neon",
    sourceDetail: "Localidad donde se ubica la propiedad",
    applicableKinds: ["arras", "senal_compra", "oferta_firme"],
    exampleValue: "Madrid",
    isArray: false,
  },
  {
    path: "property.cadastralReference",
    label: "Referencia catastral",
    category: "inmueble",
    tsType: "string",
    sourceType: "neon",
    sourceDetail: "Codigo catastral de la propiedad",
    applicableKinds: ["arras", "senal_compra", "oferta_firme"],
    exampleValue: "1234567AB1234N0001XX",
    isArray: false,
  },
  {
    path: "property.urbanDescriptionLine",
    label: "Descripcion de la finca",
    category: "inmueble",
    tsType: "string?",
    sourceType: "neon",
    sourceDetail: "Descripcion urbanistica del inmueble",
    applicableKinds: ["arras"],
    exampleValue: "URBANA: Piso vivienda en planta tercera",
    isArray: false,
  },
  {
    path: "property.registryOfficeName",
    label: "Registro de la Propiedad",
    category: "inmueble",
    tsType: "string?",
    sourceType: "inmovilla",
    sourceDetail: "Nombre del registro de la propiedad correspondiente",
    applicableKinds: ["arras"],
    exampleValue: "Registro de la Propiedad n. 5 de Madrid",
    isArray: false,
  },
  {
    path: "property.fincaNumber",
    label: "Numero de finca",
    category: "inmueble",
    tsType: "string?",
    sourceType: "inmovilla",
    sourceDetail: "Numero de finca registral",
    applicableKinds: ["arras"],
    exampleValue: "12345",
    isArray: false,
  },
  {
    path: "property.cru",
    label: "CRU (Codigo Registral)",
    category: "inmueble",
    tsType: "string?",
    sourceType: "inmovilla",
    sourceDetail: "Codigo Registral Unico del inmueble",
    applicableKinds: ["arras"],
    exampleValue: "28000000012345",
    isArray: false,
  },

  // ── Nuestra empresa ────────────────────────────────────────────────────────
  {
    path: "agency.companyLegalName",
    label: "Nombre de la empresa",
    category: "agencia",
    tsType: "string",
    sourceType: "config",
    sourceDetail: "Razon social de Urus Capital Group",
    applicableKinds: ["oferta_firme", "senal_compra"],
    exampleValue: "URUS CAPITAL GROUP S.L.",
    isArray: false,
  },
  {
    path: "agency.companyTaxId",
    label: "CIF de la empresa",
    category: "agencia",
    tsType: "string",
    sourceType: "config",
    sourceDetail: "CIF fiscal de Urus Capital Group",
    applicableKinds: ["oferta_firme", "senal_compra"],
    exampleValue: "B12345678",
    isArray: false,
  },
  {
    path: "agency.representative.fullName",
    label: "Nombre del representante",
    category: "agencia",
    tsType: "NaturalPerson.fullName",
    sourceType: "config",
    sourceDetail: "Persona que firma en nombre de la empresa",
    applicableKinds: ["oferta_firme", "senal_compra"],
    exampleValue: "Juan Perez Gomez",
    isArray: false,
  },
  {
    path: "agency.depositBankAccount.iban",
    label: "IBAN de la empresa",
    category: "agencia",
    tsType: "BankAccount.iban",
    sourceType: "config",
    sourceDetail: "Cuenta donde se reciben depositos y senales",
    applicableKinds: ["oferta_firme", "senal_compra"],
    exampleValue: "ES12 0000 0000 0000 0000 0000",
    isArray: false,
  },

  // ── Importes ──────────────────────────────────────────────────────────────
  {
    path: "totalPurchasePrice",
    label: "Precio de compraventa",
    category: "importes",
    tsType: "MoneyEUR",
    sourceType: "input",
    sourceDetail: "Precio total pactado entre comprador y vendedor",
    applicableKinds: ["arras"],
    exampleValue: "250.000,00 EUR",
    isArray: false,
    formatFn: "formatMoneyEur",
  },
  {
    path: "arrasAmount",
    label: "Importe de arras",
    category: "importes",
    tsType: "MoneyEUR",
    sourceType: "input",
    sourceDetail: "Cantidad entregada como senal de arras",
    applicableKinds: ["arras"],
    exampleValue: "25.000,00 EUR",
    isArray: false,
    formatFn: "formatMoneyEur",
  },
  {
    path: "remainderAtPublicDeed",
    label: "Resto pendiente a escritura",
    category: "importes",
    tsType: "MoneyEUR",
    sourceType: "derived",
    sourceDetail: "Se calcula automaticamente: precio total menos arras",
    applicableKinds: ["arras"],
    exampleValue: "225.000,00 EUR",
    isArray: false,
    formatFn: "formatMoneyEur",
  },
  {
    path: "offeredPrice",
    label: "Precio ofrecido",
    category: "importes",
    tsType: "MoneyEUR",
    sourceType: "input",
    sourceDetail: "Cantidad que ofrece el comprador por la propiedad",
    applicableKinds: ["oferta_firme", "senal_compra"],
    exampleValue: "240.000,00 EUR",
    isArray: false,
    formatFn: "formatMoneyEur",
  },
  {
    path: "listingPrice",
    label: "Precio publicado",
    category: "importes",
    tsType: "MoneyEUR",
    sourceType: "neon",
    sourceDetail: "Precio de venta actual de la propiedad",
    applicableKinds: ["oferta_firme"],
    exampleValue: "260.000,00 EUR",
    isArray: false,
    formatFn: "formatMoneyEur",
  },
  {
    path: "offerDeposit",
    label: "Deposito de la oferta",
    category: "importes",
    tsType: "MoneyEUR",
    sourceType: "input",
    sourceDetail: "Cantidad que deposita el ofertante como garantia",
    applicableKinds: ["oferta_firme"],
    exampleValue: "3.000,00 EUR",
    isArray: false,
    formatFn: "formatMoneyEur",
  },
  {
    path: "senalAmount",
    label: "Importe de la senal",
    category: "importes",
    tsType: "MoneyEUR",
    sourceType: "input",
    sourceDetail: "Cantidad entregada como senal de reserva",
    applicableKinds: ["senal_compra"],
    exampleValue: "10.000,00 EUR",
    isArray: false,
    formatFn: "formatMoneyEur",
  },
  {
    path: "arrasPaymentAccount.iban",
    label: "IBAN para pago de arras",
    category: "importes",
    tsType: "BankAccount.iban",
    sourceType: "input",
    sourceDetail: "Cuenta bancaria donde se transfieren las arras",
    applicableKinds: ["arras"],
    exampleValue: "ES91 2100 0418 4502 0005 1332",
    isArray: false,
  },
  {
    path: "arrasPaymentAccount.bankName",
    label: "Banco para pago de arras",
    category: "importes",
    tsType: "BankAccount.bankName",
    sourceType: "input",
    sourceDetail: "Entidad bancaria de la cuenta de arras",
    applicableKinds: ["arras"],
    exampleValue: "CaixaBank",
    isArray: false,
  },
  {
    path: "arrasPaymentAccount.holdersLine",
    label: "Titular de la cuenta de arras",
    category: "importes",
    tsType: "BankAccount.holdersLine",
    sourceType: "input",
    sourceDetail: "Nombre del titular de la cuenta donde se depositan arras",
    applicableKinds: ["arras"],
    exampleValue: "Pedro Martinez Ruiz",
    isArray: false,
  },
  {
    path: "arrasAmountAfterAcceptance",
    label: "Arras tras aceptacion de oferta",
    category: "importes",
    tsType: "MoneyEUR",
    sourceType: "input",
    sourceDetail: "Importe de arras previsto tras aceptar la oferta",
    applicableKinds: ["oferta_firme"],
    exampleValue: "25.000,00 EUR",
    isArray: false,
    formatFn: "formatMoneyEur",
  },

  // ── Plazos y Fechas ────────────────────────────────────────────────────────
  {
    path: "documentDateIso",
    label: "Fecha del contrato",
    category: "plazos",
    tsType: "string (ISO)",
    sourceType: "input",
    sourceDetail: "Fecha en la que se genera el documento",
    applicableKinds: ALL_KINDS,
    exampleValue: "20 de abril de 2026",
    isArray: false,
    formatFn: "formatDateEsFromIso",
  },
  {
    path: "signPlace",
    label: "Lugar de firma",
    category: "plazos",
    tsType: "string",
    sourceType: "input",
    sourceDetail: "Ciudad donde se firmara el contrato",
    applicableKinds: ALL_KINDS,
    exampleValue: "Madrid",
    isArray: false,
  },
  {
    path: "timelines.maxDeedDateIso",
    label: "Fecha limite para escritura",
    category: "plazos",
    tsType: "string (ISO)",
    sourceType: "input",
    sourceDetail: "Fecha maxima para firmar ante notario",
    applicableKinds: ["arras"],
    exampleValue: "15 de julio de 2026",
    isArray: false,
    formatFn: "formatDateEsFromIso",
  },
  {
    path: "timelines.maxKeysHandoverDateIso",
    label: "Fecha limite entrega de llaves",
    category: "plazos",
    tsType: "string (ISO)",
    sourceType: "input",
    sourceDetail: "Fecha maxima para entregar las llaves al comprador",
    applicableKinds: ["arras"],
    exampleValue: "15 de julio de 2026",
    isArray: false,
    formatFn: "formatDateEsFromIso",
  },
  {
    path: "timelines.convocatoriaNotaryMinNaturalDays",
    label: "Dias de preaviso al notario",
    category: "plazos",
    tsType: "number",
    sourceType: "input",
    sourceDetail: "Dias minimos de antelacion para citar al notario",
    applicableKinds: ["arras", "senal_compra"],
    exampleValue: "7 dias",
    isArray: false,
  },
  {
    path: "timelines.offerValidityNaturalDays",
    label: "Dias de validez de la oferta",
    category: "plazos",
    tsType: "number",
    sourceType: "input",
    sourceDetail: "Cuantos dias tiene el vendedor para aceptar o rechazar",
    applicableKinds: ["oferta_firme"],
    exampleValue: "3 dias",
    isArray: false,
  },
  {
    path: "timelines.arrasSigningMaxNaturalDaysFromAcceptance",
    label: "Plazo para firma de arras",
    category: "plazos",
    tsType: "number",
    sourceType: "input",
    sourceDetail: "Dias desde la aceptacion para firmar contrato de arras",
    applicableKinds: ["oferta_firme"],
    exampleValue: "15 dias",
    isArray: false,
  },
  {
    path: "timelines.escrituraMaxNaturalDaysFromArrasSignature",
    label: "Plazo para escritura desde arras",
    category: "plazos",
    tsType: "number",
    sourceType: "input",
    sourceDetail: "Dias desde la firma de arras para escriturar",
    applicableKinds: ["oferta_firme"],
    exampleValue: "60 dias",
    isArray: false,
  },
  {
    path: "timelines.businessDaysToArrasContract",
    label: "Dias para firmar arras",
    category: "plazos",
    tsType: "number",
    sourceType: "input",
    sourceDetail: "Dias habiles disponibles para formalizar el contrato de arras",
    applicableKinds: ["senal_compra"],
    exampleValue: "10 dias",
    isArray: false,
  },

  // ── Opciones del contrato ─────────────────────────────────────────────────
  {
    path: "flags.arrasRegime",
    label: "Tipo de arras",
    category: "flags",
    tsType: "ArrasLegalRegime",
    sourceType: "input",
    sourceDetail: "Penitenciales (se puede desistir) o confirmatorias (obligatorio cumplir)",
    applicableKinds: ["arras"],
    exampleValue: "Penitenciales",
    isArray: false,
  },
  {
    path: "flags.keysHandover",
    label: "Entrega de llaves",
    category: "flags",
    tsType: "KeysHandoverMode",
    sourceType: "input",
    sourceDetail: "Cuando se entregan las llaves al comprador",
    applicableKinds: ["arras", "senal_compra"],
    exampleValue: "El mismo dia de la escritura",
    isArray: false,
  },
  {
    path: "flags.validitySubjectToSellerReceipt",
    label: "Validez sujeta a cobro del vendedor",
    category: "flags",
    tsType: "boolean",
    sourceType: "input",
    sourceDetail: "El contrato solo es valido cuando el vendedor confirme haber cobrado",
    applicableKinds: ["arras"],
    exampleValue: "No",
    isArray: false,
  },
  {
    path: "flags.includeFinancingFallbackClause",
    label: "Clausula de financiacion",
    category: "flags",
    tsType: "boolean",
    sourceType: "input",
    sourceDetail: "Incluir clausula de proteccion si el comprador no obtiene hipoteca",
    applicableKinds: ["senal_compra"],
    exampleValue: "No",
    isArray: false,
  },
  {
    path: "flags.includePropertyAcceptanceSection",
    label: "Seccion de aceptacion/rechazo",
    category: "flags",
    tsType: "boolean",
    sourceType: "input",
    sourceDetail: "Incluir apartado donde el vendedor acepta o rechaza la oferta",
    applicableKinds: ["oferta_firme"],
    exampleValue: "Si",
    isArray: false,
  },

  // ── Jurisdiccion ──────────────────────────────────────────────────────────
  {
    path: "jurisdiction.courtsMunicipality",
    label: "Ciudad de los juzgados",
    category: "jurisdiccion",
    tsType: "string",
    sourceType: "input",
    sourceDetail: "Ciudad cuyos juzgados resuelven conflictos del contrato",
    applicableKinds: ALL_KINDS,
    exampleValue: "Madrid",
    isArray: false,
  },
];

export function getVariablesForKind(kind: ContractDocumentKind): VariableCatalogEntry[] {
  return VARIABLE_CATALOG.filter((v) => v.applicableKinds.includes(kind));
}

export function getVariablesByCategory(kind: ContractDocumentKind): Record<VariableCategory, VariableCatalogEntry[]> {
  const forKind = getVariablesForKind(kind);
  const result: Record<string, VariableCatalogEntry[]> = {};
  for (const entry of forKind) {
    if (!result[entry.category]) result[entry.category] = [];
    result[entry.category].push(entry);
  }
  return result as Record<VariableCategory, VariableCatalogEntry[]>;
}

export const VARIABLE_CATEGORY_LABELS: Record<VariableCategory, string> = {
  comprador_vendedor: "Personas",
  inmueble: "Inmueble",
  agencia: "Nuestra empresa",
  importes: "Importes y cuentas",
  plazos: "Plazos y fechas",
  flags: "Opciones del contrato",
  jurisdiccion: "Jurisdiccion",
};
