-- AlterEnum
ALTER TYPE "EventType" ADD VALUE 'POST_VISITA_DECIDIDA';

-- AlterEnum
ALTER TYPE "EventType" ADD VALUE 'DEMANDA_REPERFILADO_SOLICITADO';

-- AlterEnum
ALTER TYPE "EventType" ADD VALUE 'DEMANDA_BAJA_SOLICITADA';
